import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tiktokRouter from "./tiktok";
import authRouter from "./auth";
import regionsRouter from "./regions";
import propertyTypesRouter from "./propertyTypes";
import propertiesRouter from "./properties";
import usersRouter from "./users";
import inquiriesRouter from "./inquiries";
import finishingRequestsRouter from "./finishingRequests";
import propertyRequestsRouter from "./propertyRequests";
import customerPropertyRequestsRouter from "./customerPropertyRequests";
import aiConsultantRouter from "./aiConsultant";
import settingsRouter from "./settings";
import adsAnalyticsRouter from "./adsAnalytics";
import adsManagementRouter from "./adsManagement";
import smartBannersRouter from "./smartBanners";
import activityLogsRouter from "./activityLogs";
import visitorsRouter from "./visitors";
import finishingGalleryRouter from "./finishingGallery";
import aboutPageRouter from "./aboutPage";
import storageRouter from "./storage";
import contractsRouter from "./contracts";
import cloudinaryRouter from "./cloudinary";

const router: IRouter = Router();

router.use(healthRouter);
router.use(tiktokRouter);
router.use(authRouter);
router.use(regionsRouter);
router.use(propertyTypesRouter);
router.use(propertiesRouter);
router.use(usersRouter);
router.use(inquiriesRouter);
router.use(finishingRequestsRouter);
router.use(propertyRequestsRouter);
router.use(customerPropertyRequestsRouter);
router.use(aiConsultantRouter);
router.use(settingsRouter);
router.use(adsAnalyticsRouter);
router.use(adsManagementRouter);
router.use(smartBannersRouter);
router.use(activityLogsRouter);
router.use(visitorsRouter);
router.use(finishingGalleryRouter);
router.use(aboutPageRouter);
router.use(storageRouter);
router.use(contractsRouter);
router.use(cloudinaryRouter);

export default router;
