import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseWorkbookBytes, type ParsedProperty } from "../src/lib/propertyImport";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_XLSX = resolve(
  __dirname,
  "../../../attached_assets/14___يونيو_-_Snapshot_النهائي_1782613282995.xlsx",
);
const OUT = resolve(__dirname, "../src/data/seedProperties.ts");
const OUT_SOURCES = resolve(__dirname, "../src/data/seedSources.ts");
const OUT_API = resolve(__dirname, "../../api-server/src/data/seedProperties.ts");

const bytes = new Uint8Array(readFileSync(SRC_XLSX));
const { items, sheets } = parseWorkbookBytes(bytes);

console.log("Sheets parsed:");
for (const s of sheets) console.log(`  - ${s.name}: ${s.count}`);
console.log(`Total: ${items.length}`);

const seen = new Map<string, number>();
const BASE = Date.parse("2026-06-14T12:00:00.000Z");
const sources: Record<string, string> = {};

const records = items.map((p: ParsedProperty, i: number) => {
  let code = p.code || `ALM-${10000 + i}`;
  const n = seen.get(code) ?? 0;
  seen.set(code, n + 1);
  if (n > 0) code = `${code}-${n + 1}`;
  const { source, ...rest } = p;
  if (source) sources[code] = source;
  return {
    ...rest,
    code,
    id: `seed-${i + 1}`,
    createdAt: new Date(BASE - i * 60000).toISOString(),
  };
});

const dupCodes = [...seen.entries()].filter(([, c]) => c > 1);
if (dupCodes.length) {
  console.log("Duplicate base codes (suffixed to stay unique):");
  for (const [c, n] of dupCodes) console.log(`  - ${c} x${n}`);
}

const header = `// AUTO-GENERATED by scripts/genSeed.ts — do not edit by hand.
// Source: attached_assets Excel snapshot. Re-run: pnpm --filter @workspace/alamoudi run gen:seed
import type { Property } from "@/context/DataContext";

export const SEED_PROPERTIES: Property[] = ${JSON.stringify(records, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, header, "utf8");
console.log(`Wrote ${records.length} properties -> ${OUT}`);

const sourcesHeader = `// AUTO-GENERATED by scripts/genSeed.ts — do not edit by hand.
// ADMIN-ONLY private data (deal source). Import this ONLY from admin-only,
// code-split modules so it never ships in the public bundle.
export const SEED_SOURCES: Record<string, string> = ${JSON.stringify(sources, null, 2)};
`;
writeFileSync(OUT_SOURCES, sourcesHeader, "utf8");
console.log(`Wrote ${Object.keys(sources).length} sources -> ${OUT_SOURCES}`);

const apiHeader = `// AUTO-GENERATED by scripts/genSeed.ts — do not edit by hand.
// Source: attached_assets Excel snapshot. Re-run: pnpm --filter @workspace/alamoudi run gen:seed
import type { InsertProperty } from "@workspace/db";

export const SEED_PROPERTIES: InsertProperty[] = ${JSON.stringify(records, null, 2)};
`;
writeFileSync(OUT_API, apiHeader, "utf8");
console.log(`Wrote ${records.length} properties -> ${OUT_API}`);
